const slidesTranslate = {
  "russian": {
    "mainBtn": "РЕГИСТРАЦИЯ",
    "navigationLinkOne": "СЕРИЯ БОНУСОВ",
    "navigationLinkTwo": "БОНУС 100%",
    "navigationLinkThree": "1000$ ЗА ПРОГНОЗ",
    "navigationLinkFour": "ML ПЛАТИТ/ВЕРНЕТ",
    "navigationLinkFive": "4% CASHBACK",
    "navigationLinkSix": "УСЛОВИЯ",
    "slideOneTextLineOne": "БОЛЬШАЯ",
    "slideOneTextLineTwo": "СЕРИЯ БОНУСОВ",
    "slideOneTextLineThree": "Больше игры - больше бонусов",
    "slideTwoTextLineOne": "БОНУС",
    "slideTwoTextLineTwo": "I00 <span>%</span>",
    "slideTwoTextLineThree": "К 1-му ДЕПОЗИТУ",
    "slideThreeTextLineOne": "КАЖДЫЙ ДЕНЬ",
    "slideThreeTextLineTwo": "I000",
    "slideThreeTextLineThree": "ЗА ВЕРНЫЙ ПРОГНОЗ",
    "slideFourTextLineOne": "ПРОИГРЫШНЫЕ СТАВКИ",
    "slideFourTextLineTwo": "НА ПЛЮС",
    "slideFourTextLineThree": "ИЛИ <span>НА ВОЗВРАТ</span>",
    "slideFiveTextLineOne": "4%",
    "slideFiveTextLineTwo": "CASHBACK",
    "slideFiveTextLineThree": "НА деПОЗИТ",
    "slideSixTitle": "УСЛОВИЯ БОНУСОВ",
    "slideSixTriggerOne": "100% к первому депозиту",
    "slideSixTriggerTwo": "1000$ ЗА ВЕРНЫЙ ПРОГНОЗ",
    "slideSixTriggerThree": "MAXLINE ПЛАТИТ И ВЕРНЕТ",
    "slideSixTriggerFour": "4% CASHBACK",
  },
  "english": {
    "mainBtn": "REGISTRATION",
    "navigationLinkOne": "SERIES OF BONUSES",
    "navigationLinkTwo": "BONUS 100%",
    "navigationLinkThree": "1000 $ PER FORECAST",
    "navigationLinkFour": "ML PAYS / RETURNS",
    "navigationLinkFive": "4% CASHBACK",
    "navigationLinkSix": "CONDITIONS",
    "slideOneTextLineOne": "BIG",
    "slideOneTextLineTwo": "SERIES OF BONUSES",
    "slideOneTextLineThree": "More game - more bonuses",
    "slideTwoTextLineOne": "BONUS",
    "slideTwoTextLineTwo": "I00 <span>%</span>",
    "slideTwoTextLineThree": "FIRST deposit",
    "slideThreeTextLineOne": "everyday",
    "slideThreeTextLineTwo": "I000",
    "slideThreeTextLineThree": "FOR TRUE FORECAST",
    "slideFourTextLineOne": "LOSING BETS",
    "slideFourTextLineTwo": "ON PLUS",
    "slideFourTextLineThree": "OR <span>REFUND</span>",
    "slideFiveTextLineOne": "4%",
    "slideFiveTextLineTwo": "CASHBACK",
    "slideFiveTextLineThree": "on deposit",
    "slideSixTitle": "CONDITIONS",
    "slideSixTriggerOne": "100% to the first deposit",
    "slideSixTriggerTwo": "1000$ FOR CORRECT FORECAST",
    "slideSixTriggerThree": "MAXLINE PAYS AND RETURNS",
    "slideSixTriggerFour": "4% CASHBACK",
  }
}