const translate = {
  "russian": {
    "mainBtn": "РЕГИСТРАЦИЯ",
    'navigationLinkOne': 'СЕРИЯ БОНУСОВ',
    'navigationLinkTwo': 'БОНУС 100%',
    'navigationLinkThree': '1000$ ЗА ПРОГНОЗ',
    'navigationLinkFour': 'ML ПЛАТИТ/ВЕРНЕТ',
    'navigationLinkFive': '4% CASHBACK',
    'navigationLinkSix': 'УСЛОВИЯ',
    "slideOneTextLineOne": "БОЛЬШАЯ",
    "slideOneTextLineTwo": "СЕРИЯ БОНУСОВ",
    "slideOneTextLineThree": "Больше игры - больше бонусов",
    "slideTwoTextLineOne": "БОНУС",
    "slideTwoTextLineTwo": "I00",
    "slideTwoTextLineThree": "К 1-му ДЕПОЗИТУ",
    "slideThreeTextLineOne": "КАЖДЫЙ ДЕНЬ",
    "slideThreeTextLineTwo": "I000",
    "slideThreeTextLineThree": "ЗА ВЕРНЫЙ ПРОГНОЗ",
  },
  "english": {
    "mainBtn": "REGISTRATION",
    'navigationLinkOne': 'SERIES OF BONUSES',
    'navigationLinkTwo': 'BONUS 100%',
    'navigationLinkThree': '1000 $ PER FORECAST',
    'navigationLinkFour': 'ML PAYS / RETURNS',
    'navigationLinkFive': '4% CASHBACK',
    'navigationLinkSix': 'CONDITIONS',
    "slideOneTextLineOne": "BIG",
    "slideOneTextLineTwo": "SERIES OF BONUSES",
    "slideOneTextLineThree": "More game - more bonuses",
    "slideTwoTextLineOne": "BONUS",
    "slideTwoTextLineTwo": "I00",
    "slideTwoTextLineThree": "FIRST deposit",
    "slideThreeTextLineOne": "everyday",
    "slideThreeTextLineTwo": "I000",
    "slideThreeTextLineThree": "FOR TRUE FORECAST",
  }
}